package com.serverlessspringdynamo.serverlessspringdynamo.Domain;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName="CitizenDetails")
public class Citizen implements Serializable{
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private Long sso_id;
	@DynamoDBAttribute(attributeName="age")
	private int age;
	@DynamoDBAttribute(attributeName="Address")
	private Address adress;
		
}
